Re factor de Send Message + Multi messaging (pro feature)
Franbarbier/dragonchat-front pull request #124
Opened 2024-02-09 23:32 UTC by Franbarbier

[] Cambio de numero de wpp de soporte (me pidio teo)
[] Refactor de la funcion de envio de mensajes: Delay minimo obligatorio (3 segs), espera el response del envio anterior para ejectuar el siguiente, delay, bouqes y pausa
[] "Nueva difusion" ya no refresca la pagina.. te lleva a la primer tarjeta con los contactos anteriores ya cargados
[] Optimizacion codigo anti-bloquer
[] Mini bug del anti bloquer que apretando "settings" hacia el switch de on/off y no guardaba valores correctamente
[] Correccion de cuando sale el modal "Finish sending" ahora sale bien, solo cuando llega el response del ultimo envio

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2024-02-11 19:06 UTC, apocales commented on components/WppBtn/WppBtn.tsx
> +                        <a href="https://wa.me/56946581170?text=Hola!%20Me%20contacto%20desde%20dragonchat%20por%20" target="_blank">
creo que en este caso seria mejor usar una funcion para encodear el texto, algo asi
```
<a href="https://wa.me/56946581170?text={encodeURIComponent('Hola! Me contacto desde dragonchat por ')} target="_blank">
```
esto para entender los textos de una forma mas simple

2024-02-11 19:07 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +    setMessages : (message: Array<any[]>) => void;
porque cambiamos `string` por `any`?

2024-02-11 19:08 UTC, apocales commented on components/cards/Card/MessageFree.tsx
> +    setMessages : (mensajes: any[]) => void;
porque cambiamos `string` por `any`?

2024-02-11 19:09 UTC, apocales commented on components/cards/Card/SendFree.tsx
> +  async function sendMove(cnt) {
podríamos definir el tipo de cnt para que sea mas fácil de entender para cualquiera que vaya a editar este código en el futuro

2024-02-11 19:10 UTC, apocales commented on components/cards/Card/SendFree.tsx
> +                      {/* {contact.estado == STATUS.PENDING && ( */}
quitemos este comentario

2024-02-11 19:11 UTC, apocales commented on components/cards/ModalFinish/ModalFinish.tsx
> +                {/* <h3>¡Tu envío ha finalizado con éxito!</h3> */}
quitemos el comentario

2024-02-11 19:13 UTC, apocales commented on components/cards/MultiMessages/MultiMessages.tsx
> +    setMessages : (message: any) => void;
porque cambiamos `string` por `any`?

2024-02-11 19:14 UTC, apocales commented on components/cards/MultiMessages/MultiMessages.tsx
> +                                {/* <img src="/close.svg" /> */}
quitemos los comentarios

2024-02-12 15:50 UTC, Franbarbier commented on components/cards/BasicMessages/BasicMessages.tsx
> +    setMessages : (message: Array<any[]>) => void;
lo puse porque no sabia como poner como type un array de arrays de strings, pero ahi lo corrijo 👍

2024-02-12 23:24 UTC, alfredopuertacl requested changes

2024-02-12 23:24 UTC, alfredopuertacl commented on components/WppBtn/WppBtn.tsx
> +    const whatsappLink = wppLink(56946581170, 'Hola! Me contacto desde dragonchat por')
pero este es mi numero no debe ir, como soporte

2024-02-14 01:35 UTC, apocales requested changes

2024-02-14 01:35 UTC, apocales commented on components/cards/CardsContFree.tsx
> +                const emptyMess = messages.some(subarray => subarray.includes(""))
esta condición no la entiendo bien, porque si el array tiene al menos un elemento esta condición siempre data true, eso es correcto????

2024-02-16 19:01 UTC, Franbarbier commented on components/WppBtn/WppBtn.tsx
> +    const whatsappLink = wppLink(56946581170, 'Hola! Me contacto desde dragonchat por')
ajja eso me dijo teo!

2024-02-16 23:29 UTC, apocales approved these changes

2024-02-17 00:02 UTC, alfredopuertacl approved these changes

2024-02-17 00:34 UTC, merged