Cambios multimensajes que pidio teo
Franbarbier/dragonchat-front pull request #129
Opened 2024-02-20 23:15 UTC by Franbarbier

Cambios visuales del multi mensaje
---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2024-02-21 02:38 UTC, apocales requested changes

2024-02-21 02:38 UTC, apocales commented on components/cards/MultiMessages/MultiMessages.module.css
> +    /* border: 0.3em solid var(--newPink); */
quitar comentario

2024-02-21 02:38 UTC, apocales commented on components/cards/MultiMessages/MultiMessages.module.css
> +    /* padding-top: 9.5%; */
quitar comentario

2024-02-21 02:38 UTC, apocales commented on components/cards/MultiMessages/MultiMessages.tsx
> +    console.log(messages)
quitar console log

2024-02-27 00:14 UTC, apocales approved these changes

2024-02-29 22:37 UTC, alfredopuertacl commented on components/cards/MultiMessages/MultiMessages.tsx
> +    console.log(kkkkk(), LineDash)
este console es necesario?

2024-02-29 22:40 UTC, Franbarbier commented on components/cards/MultiMessages/MultiMessages.tsx
> +    console.log(kkkkk(), LineDash)
😳

2024-04-02 15:48 UTC, merged