Correcciones mencionadas en el video de User Feedback #19 + Alguna que otra observación aislada
Franbarbier/dragonchat-front pull request #132
Opened 2024-03-05 17:32 UTC by Franbarbier

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2024-03-06 23:29 UTC, apocales requested changes

2024-03-06 23:29 UTC, apocales commented on components/cards/Card/RecipientsFree.tsx
> +            // Perform the action for Shift + click
estos comentarios deben resolverse?

2024-03-06 23:29 UTC, apocales commented on components/cards/Card/RecipientsFree.tsx
> +            }
creo que esto se podria resumir en 
```
selectedList[index].selected = !selectedList[index].selected
```

2024-03-06 23:29 UTC, apocales commented on components/cards/CardsContFree.tsx
> +            {/* Si esta en ultima card y ya termino de enviar muestra el refresh */}
quitar comentario

2024-03-06 23:29 UTC, apocales commented on components/cards/ModalShieldOptions/ModalShieldOptions.tsx
> +        // if starts with 0, remove the 0 and let the typed number
quitar comentario

2024-03-06 23:29 UTC, apocales commented on components/cards/Card/MessageFree.tsx
> +        if (event.key === 'Enter' && !event.shiftKey) {
quiza podriamos tener un enum para los `event.key` values

2024-03-08 13:33 UTC, Franbarbier commented on components/cards/Card/RecipientsFree.tsx
> +            // Perform the action for Shift + click
son de guia para el codigo, documentacion. Para entenderlo mas facil

2024-03-08 15:00 UTC, Franbarbier commented on components/cards/Card/RecipientsFree.tsx
> +            // Perform the action for Shift + click
Se conserva

2024-03-08 15:00 UTC, Franbarbier commented on components/cards/CardsContFree.tsx
> +            {/* Si esta en ultima card y ya termino de enviar muestra el refresh */}
Se conserva

2024-03-08 15:13 UTC, Franbarbier commented on components/cards/Card/MessageFree.tsx
> +        if (event.key === 'Enter' && !event.shiftKey) {
Dale

2024-03-08 15:39 UTC, Franbarbier commented on components/cards/ModalShieldOptions/ModalShieldOptions.tsx
> +        // if starts with 0, remove the 0 and let the typed number
se conserva

2024-03-08 16:38 UTC, apocales approved these changes

2024-03-08 17:24 UTC, alfredopuertacl approved these changes

2024-03-08 17:24 UTC, merged