Feature/add token header
Franbarbier/dragonchat-front pull request #57
Opened 2023-06-05 20:03 UTC by NicolasArias1

Se añade token de autenticación en controller de conexión whatsapp

2023-06-05 21:09 UTC, alfredopuertacl approved these changes

2023-06-05 21:09 UTC, alfredopuertacl commented on api/apiSenderWhatsappController.tsx
> +        const url = `${API_URL}/client/close_client/${userId}`;
aca elimina el **${userId}** no lo usaremos

2023-06-05 21:13 UTC, NicolasArias1 commented on api/apiSenderWhatsappController.tsx
> +        const url = `${API_URL}/client/close_client/${userId}`;
cambiado

2023-06-05 21:48 UTC, alfredopuertacl approved these changes

2023-06-07 15:49 UTC, Franbarbier approved these changes

2023-06-07 16:01 UTC, Franbarbier commented
<img width="1224" alt="image" src="https://github.com/Franbarbier/dragonchat-front/assets/48157540/b12f8b82-e4dc-402a-9c0b-c21804e1c651">

Cuando lo quiero correr en vercel sale este error. Hay que eliminar esta fila, y deberia estar todo OK
<img width="474" alt="image" src="https://github.com/Franbarbier/dragonchat-front/assets/48157540/c36830f7-79a7-4c34-9449-0defece6bf30">

2023-06-07 19:44 UTC, alfredopuertacl requested changes

2023-06-07 19:44 UTC, alfredopuertacl commented on components/EditUserProfileView/EditUserProfileView.tsx
> +import { deleteCookie, getCookie } from "cookies-next";
@NicolasArias1 las cookies no se estan borrando, podrías intentar mejor usar **next/headers** que es de next igual!

2023-06-07 20:55 UTC, closed without merging