Auth token in wsp connection controller
Franbarbier/dragonchat-front pull request #58
Opened 2023-06-07 21:10 UTC by NicolasArias1

Se añade token de autenticación en controller de conexión whatsapp

2023-06-07 23:30 UTC, apocales requested changes

2023-06-07 23:30 UTC, apocales commented on api/apiSenderWhatsappController.tsx
> +const API_URL = process.env.NEXT_PUBLIC_API_SENDER_URL;
seria bueno que moviéramos las variables de entornos a un archivo de constantes

2023-06-07 23:30 UTC, apocales commented on api/apiSenderWhatsappController.tsx
>          });
porque usamos fetch y axios??? deberíamos decidirnos por una opción

2023-06-08 17:15 UTC, NicolasArias1 commented on api/apiSenderWhatsappController.tsx
>          });
movido a una nueva tarea

2023-06-08 17:19 UTC, apocales approved these changes

2023-06-08 17:20 UTC, alfredopuertacl approved these changes

2023-06-08 17:22 UTC, merged