Feature/fix qr cookie
Franbarbier/dragonchat-front pull request #60
Opened 2023-06-09 20:00 UTC by NicolasArias1

Se corrige el mal uso de `js-cookie` en `getInitialProps` del archivo `qr.ts`

2023-06-09 22:03 UTC, alfredopuertacl commented
Hola @NicolasArias1 estuve realizando pruebas en local y en el server, pero me arroja errores al cerrar la sesión del usuario: 
<img width="752" alt="Captura de pantalla 2023-06-09 a la(s) 17 01 20" src="https://github.com/Franbarbier/dragonchat-front/assets/49530114/0c68237c-acb8-4163-a965-831322f393ca">

2023-06-10 00:06 UTC, apocales requested changes

2023-06-10 00:06 UTC, apocales commented on pages/qr.tsx
> +        Cookies.remove(process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME);
consulta, pero para verlo mas adelante, es necesario que mantengamos el uso de `js-cookie`? como ven la opción de hacer un util con cookie directamente para este manejo?

2023-06-10 02:17 UTC, NicolasArias1 commented
> Hola @NicolasArias1 estuve realizando pruebas en local y en el server, pero me arroja errores al cerrar la sesión del usuario: <img alt="Captura de pantalla 2023-06-09 a la(s) 17 01 20" width="752" src="https://user-images.githubusercontent.com/49530114/244809474-0c68237c-acb8-4163-a965-831322f393ca.png">

esto no estaba planificado en el PR, pero también se solucionó en el commit reciente

2023-06-10 02:20 UTC, NicolasArias1 commented on pages/qr.tsx
> +      const accessToken = JSON.parse(Cookies.get(process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME)).access_token;
me da a pensar que acá no aplica, ya que la constante acá sería `process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME` y esta ya está "sacada" de otro lugar

cómo sugerirías que podría quedar en el archivo de constantes?

2023-06-10 02:23 UTC, NicolasArias1 commented on pages/qr.tsx
> +        Cookies.remove(process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME);
`cookie` como tal no entrega lo mismo que `js-cookie`

- `cookie` entrega métodos utilitarios como serialize, parse, decode, etc
- `js-cookie` entrega métodos de obtención, creación eliminación, etc

de todos modos, con alfredo hemos conversado de comenzar ocupar alguna herramienta de cookies client-side que nos entregue nextjs. tengo pendiente de revisar `next/headers`.cookies()

2023-06-10 05:25 UTC, apocales commented on pages/qr.tsx
> +      const accessToken = JSON.parse(Cookies.get(process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME)).access_token;
no entiendo bien a lo que te refieres con que esta sacada de otro lugar, pero yo pensaba que podía quedar como otro export dentro del index en la carpeta de constants, algo asi
```
export const COOKIE_NAME = process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME;
```

2023-06-10 05:27 UTC, apocales commented on pages/qr.tsx
> +        Cookies.remove(process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME);
si entiendo la diferencia entre cookie y js-cookie, pero yo mencionaba que podríamos hacer una implementación manual como la que se hizo en el backoffice y que fuera compatible con front y back, pero bueno, a su momento se vera

2023-06-10 18:28 UTC, NicolasArias1 commented on pages/qr.tsx
> +      const accessToken = JSON.parse(Cookies.get(process.env.NEXT_PUBLIC_LOGIN_COOKIE_NAME)).access_token;
cambiado

2023-06-10 18:47 UTC, apocales approved these changes

2023-06-10 18:48 UTC, merged