Feature/new qr
Franbarbier/dragonchat-front pull request #65
Opened 2023-06-15 17:06 UTC by NicolasArias1

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-06-15 23:50 UTC, apocales requested changes

2023-06-15 23:50 UTC, apocales commented on api/apiSenderWhatsappController.tsx
>              method: "PUT",
podríamos dejar los verbos http en un enum

2023-06-15 23:50 UTC, apocales commented on api/apiSenderWhatsappController.tsx
> +                    }
ya que en general se repiten, podríamos hacer una utilidad para obtener los headers, de paso quiza podriamos quitar la necesidad de pasar el token como parámetro, desde donde se lee el token?

2023-06-15 23:50 UTC, apocales commented on api/apiSenderWhatsappController.tsx
> +        }
no se si lo mencione en algún comentario de algun PR anterior, pero creo que seria buena idea implementar un cliente para los request con axios, así podríamos simplificar otros métodos y centralizar el manejo de errores, pero se puede dejar para mas adelante si no se puede ver ahora

2023-06-15 23:50 UTC, apocales commented on components/QrCard/QrCard.tsx
> +                        <img src={activeQr} width="75%" alt="qrWhatsappImage" onLoad={handleIsConnected} />
si es posible, evitemos los estilos en el componente

2023-06-16 17:17 UTC, NicolasArias1 commented on api/apiSenderWhatsappController.tsx
>              method: "PUT",
solo este fetch me quedaba y lo deprequé con el /disconnect

2023-06-16 17:18 UTC, NicolasArias1 commented on api/apiSenderWhatsappController.tsx
> +                    }
lo movi a un método y... el token lo pasa el front que lee la cookie client side

intenté obtener la cookie acá con cookie-js pero no lo logre :-(

2023-06-16 17:19 UTC, NicolasArias1 commented on api/apiSenderWhatsappController.tsx
> +        }
sentémonos a mejorar esto, incluso hooks sería mejor? pero para llegar una implementación mejor, yo solo mejoré lo que había

2023-06-16 17:19 UTC, NicolasArias1 commented on components/QrCard/QrCard.tsx
> +                        <img src={activeQr} width="75%" alt="qrWhatsappImage" onLoad={handleIsConnected} />
solo por tema de que estamos apurados, lo paso a un siguiente pr

el repo en general tiene algunas cositas así que habría que mejorar si o si, yo estoy de acuerdo contigo pablo

2023-06-16 17:25 UTC, apocales commented on api/apiSenderWhatsappController.tsx
> +                    }
vale, revisemos como podemos hacer lo del token en un próximo Pr

2023-06-16 17:26 UTC, apocales commented on api/apiSenderWhatsappController.tsx
> +        }
perfecto, lo resolveremos en una implementación próxima

2023-06-16 17:27 UTC, apocales approved these changes

2023-06-16 19:42 UTC, merged