Agregue pagina 404
Franbarbier/dragonchat-front pull request #66
Opened 2023-06-15 18:13 UTC by Franbarbier

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-06-15 22:59 UTC, alfredopuertacl requested changes
Intenta usar en las ramas los nombres correspondientes, por ejemplo en esta deberia ser **feature** no _feat_

2023-06-15 22:59 UTC, alfredopuertacl commented on pages/404.tsx
> +            {/* <NotFound /> */}
deberiamos eliminar esto, si no lo usaremos.

2023-06-15 22:59 UTC, alfredopuertacl commented on pages/404.tsx
> +            </MainCont> */}
igual eliminarlo xD

2023-06-15 23:41 UTC, apocales requested changes

2023-06-15 23:41 UTC, apocales commented on components/Err404/NotFound.module.css
> +  color: var(--newPink);
usamos variables?? porque si es asi podriamos colocar mas variables para colores y para algunas medidas

2023-06-15 23:41 UTC, apocales commented on components/Err404/NotFound.tsx
> +
si no usamos props no es necesario definir un tipado ni pasar un objeto vacío

2023-06-15 23:41 UTC, apocales commented on pages/404.tsx
> +const NotFoundView : NextPageWithLayout<GralProps> = () => {
no incluyamos un tipado si no usaremos las props

2023-06-16 16:59 UTC, Franbarbier commented on components/Err404/NotFound.module.css
> +  color: var(--newPink);
Mas que nada los colores principales estan en variables, Medidas en general viene con el componente si es que se repite mas de una vez

2023-06-16 18:17 UTC, Franbarbier commented
> Intenta usar en las ramas los nombres correspondientes, por ejemplo en esta deberia ser **feature** no _feat_

"feat" en ingles y en la jerga es una abreviación de feature, lo use para acortarlo, pero a partir de ahora lo escribo completo  🫡 👌

2023-06-16 18:20 UTC, apocales commented on components/Err404/NotFound.module.css
> +  color: var(--newPink);
ok, entonces dejemos dentro de las mejoras pendientes el implementar mas variables para temas standar

2023-06-16 18:20 UTC, apocales approved these changes

2023-06-16 18:21 UTC, alfredopuertacl approved these changes

2023-06-16 19:42 UTC, merged