Estilos varios, responsive, global fixes
Franbarbier/dragonchat-front pull request #71
Opened 2023-06-22 22:19 UTC by Franbarbier

-Optimizar a mobile:
        notificaciones √ 
	opciones + tuerquita del menú √
	Planilla width
        Shield options 
        Modal shield options√
        Corregir el tic/cruz de enviados √
        Modal referí amigo √
        Modal importar contactos  √

-No se puede eliminar el primer caracter de nombre/num en recipientes √
-Sacar orangeBtn component en login √
-sale cortado el titulo de recuperar pass + no se puede volver al login √
-cuando termine de enviar te diga “enviar de vuelta y no te deje volver √
-que en cada logout debería haber un loading √
-al desvincular wsp, sigue saliendo un alert y podría salir un Notification √

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-06-23 17:33 UTC, apocales requested changes

2023-06-23 17:33 UTC, apocales commented on components/EditUserProfileView/EditUserProfileView.tsx
>          Router.push("/login");
usemos enums para las rutas

2023-06-23 17:33 UTC, apocales commented on components/RecoverPasswordView/RecoverPasswordView.tsx
> +    router.push("/login");
usemos enum para las rutas

2023-06-23 17:33 UTC, apocales commented on pages/qr.tsx
>          Router.push("/login");
usemos enums para las rutas

2023-06-24 17:51 UTC, alfredopuertacl approved these changes

2023-06-24 17:51 UTC, alfredopuertacl commented on components/EditUserProfileView/EditUserProfileView.tsx
>        Router.push("/qr");
igual usar enums aca

2023-06-24 17:51 UTC, alfredopuertacl commented on components/EditUserProfileView/EditUserProfileView.tsx
>        // (error.response.data.error);
eliminar este comment

2023-06-24 17:51 UTC, alfredopuertacl commented on components/RecoverPasswordView/RecoverPasswordView.tsx
>      Router.prefetch('/new_password');
igual usar enums

2023-06-24 23:42 UTC, Franbarbier commented on components/CustomColorBtn/CustomColorBtn.tsx
> +    onClick: (arg:any) => void;
Dale hago eso, pero porque? Es un componente super global, un boton, que puede recibir casi cualquier cosa.

2023-06-24 23:46 UTC, Franbarbier commented on components/cards/CardsContFree.tsx
> +                    setActiveCard(activeCard-1)
Hay un useState que es <number> y se fija la active card, o sea de las tres etapas del envio, cada uno tiene un componente card, donde seteas los recipientes, donde redactas el mensaje y donde ejecutas el envio. cada una tiene un id, entonces ese codigo significa: que en caso que este en la card 3, la de ejecutar el envio, si uno quiere volver al paso anterior resta un numero del id de la active card actual, ese if se fija si ya se hizo el envio no te deja volver (para que puedas cambiar el mensaje o la lista y volver a enviar y se crushee todo, eventualmente se puede mejorar este control igual, que te deje volver pero no puedas modificar los datos y demas
)

2023-06-25 00:59 UTC, apocales commented on components/CustomColorBtn/CustomColorBtn.tsx
> +    onClick: (arg:any) => void;
la idea del uso de typescript es restringir las propiedades que puedes usar dentro de un componente y que también te brinde una ayuda al momento de saber cuales props tienes disponibles para usar, de modo que si usas any en todas partes la utilidad que se pretende que tenga typescript no sería tal, ahora eso no significa que no se pueda usar el any (aunque en el caso de que sea necesario deberíamos verificar el uso del tipo unknown primero), solo que debemos ser mas selectivos para definir cuándo usarlo, el tipo específico que te indique es el tipo que se usa en react para los eventos onclick (esto lo hace válido para cualquier evento de botón que necesites usar), que es justamente lo que estás haciendo y tiene una definición de todas las props que podrías querer usar de estos eventos, en general para todos los eventos html tenemos estos tipos predefinidos que podemos utilizar, aparte si necesitamos incluir nuevas props personalizadas a estos eventos lo correcto sería definir un nuevo control con un nuevo evento que extienda estas propiedades

2023-06-25 01:05 UTC, apocales commented on components/cards/CardsContFree.tsx
> +                    setActiveCard(activeCard-1)
aaaa ok, ahora entendí, no es un `activeCard-1` como nombre... es una operación matemática... onda activeCard menos uno... en ese caso, para mejorar la legibilidad seria bueno que este tipo de operaciones estuvieran separadas, onda `activeCard - 1`, igual para hacer esto una mejora general deberíamos incluirlo en el linter, pero ok, no es necesario que lo consideremos ahora, pero si o si debe hacerse en la migración de componentes

2023-06-26 17:22 UTC, alfredopuertacl requested changes

2023-06-26 17:22 UTC, alfredopuertacl commented on components/EditUserProfileView/EditUserProfileView.tsx
> +      Router.push(`${ ROUTES.QR }}`);
no es necesario concatenar la variable, porque no le sigue un String. Podrías solo dejar el **ROUTES.QR** como variable.

2023-06-26 17:22 UTC, alfredopuertacl commented on components/RecoverPasswordView/RecoverPasswordView.tsx
> +    Router.prefetch(`${ROUTES.NEW_PASS}`);
igual aca sin concatenación.

2023-06-26 21:48 UTC, apocales requested changes

2023-06-26 21:48 UTC, apocales commented on components/RecoverPasswordView/RecoverPasswordView.module.css
> +    background-color: #7561ca57;
en que formato esta este color? estamos seguros de que es un color valido?

2023-06-26 21:48 UTC, apocales commented on utils/checkDevice.js
> +    };
me gusta la idea de esta función, pero igual creo que podemos pensar mejor algunos puntos, por ejemplo, porque queremos identificar si el dispositivo es un móvil, solo nos interesa la resolución de su pantalla? porque igual nos podemos encontrar con casos de tablets con una resolución mayor, como la Samsung s8 pro, tambien podriamos usar mecanismos como el del useragent para determinar esto con mayor exactitud, pero igual no creo que sea necesario hacerlo en este momento, pero es bueno considerarlo para el futuro donde podríamos hacer vistas diferenciadas para cada dispositivo, igualmente considero que en el futuro debemos hacer el manejo de los breakpoints solo en el css para mejorar la separación de responsabilidades, igual indico esto solo para que tengamos en mente una futura tarea, aparte dejo un ejemplo del uso del userAgent
```
let navegador = navigator.userAgent;
if (navigator.userAgent.match(/Android/i) || navigator.userAgent.match(/webOS/i) || navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iPod/i) || navigator.userAgent.match(/BlackBerry/i) || navigator.userAgent.match(/Windows Phone/i)) {
    console.log("Estás usando un dispositivo móvil!!");
} else {
    console.log("No estás usando un móvil");
}
```

2023-06-26 21:55 UTC, Franbarbier commented on components/RecoverPasswordView/RecoverPasswordView.module.css
> +    background-color: #7561ca57;
Sisi, es un hexadecimal con opacidad:
<img width="232" alt="image" src="https://github.com/Franbarbier/dragonchat-front/assets/48157540/7f00a9cc-1a25-46ce-8d16-95d4c9888d8c">

2023-06-26 21:59 UTC, apocales commented on components/RecoverPasswordView/RecoverPasswordView.module.css
> +    background-color: #7561ca57;
perfecto, buenisimo

2023-06-26 21:59 UTC, apocales approved these changes

2023-06-26 22:02 UTC, Franbarbier commented on utils/checkDevice.js
> +    };
Esta bien, cuando migre los componentes donde se necesita esto lo voy a pensar. En principio es porque hay unos componentes (los cuadrados traslucidos violetas con borde violeta) que depende la vista cambian el tamano (con CSS no se podia hacer) y son componentes globales a lo largo de toda la app (Tambien, como tantas otras cosas, se estructuraron de una forma y despues con todos los cambios quedo un poco obsoleta esa estructura, y como tantas otras cosa, meti parche en vez de arreglar de 0)

2023-06-26 22:08 UTC, merged