Fix/qa tasks
Franbarbier/dragonchat-front pull request #75
Opened 2023-06-26 22:49 UTC by Franbarbier

Lista de tareas asignadas a mi que salieron del feedback del QA que hicimos en grupo:
-El counter del shield Block si se vacía que quede en 0 
-Cuando se vuelve a abrir el modal shield guarde los valores del temporizador 
-Bloquear punto en input modal shield
-Cuando no se apretar “activar” que no haga turn on del times-Importar contactos modal error de redacción (Fran)
-Cambiar el archivo de template de .csv (Fran)
-Cuando cambias de pestaña no se borre el mensaje (Fran)
-Achicar la letra en modalimport contactos mobile (Fran)

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-06-27 00:11 UTC, apocales requested changes

2023-06-27 00:11 UTC, apocales commented on components/cards/Card/MessageFree.tsx
> +                            <div className={`${styles.difu_tab} ${tipoEnvio == "difusion" && styles.active_tab}`}
dejemos los tipos de envio como enums

2023-06-27 00:11 UTC, apocales commented on components/cards/CardsContFree.tsx
> +    const [tipoEnvio, setTipoEnvio] = useState<"difusion" | "conversacion">("difusion")
dejemos el tipo de envio como enum

2023-06-27 00:11 UTC, apocales commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +                <p>Puedes ver un ejemplo o descargarlo haciendo clic <a href="/Plantilla Ejemplo.numbers" >acá</a>.</p>
si el href es un archivo fijo dentro del sistema deberiamos dejarlo como una constante

2023-06-27 16:09 UTC, Franbarbier commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +                <p>Puedes ver un ejemplo o descargarlo haciendo clic <a href="/Plantilla Ejemplo.numbers" >acá</a>.</p>
Aunque solo se use una vez?

2023-07-04 23:15 UTC, apocales commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +                <p>Puedes ver un ejemplo o descargarlo haciendo clic <a href="/Plantilla Ejemplo.numbers" >acá</a>.</p>
si estamos seguros de que no se usara nuevamente, podemos dejarlo así, pero igual seria bueno hacerlo como forma de trabajo, ya que no siempre estaremos seguros de que no se usará en otros lugares en el futuro

2023-07-04 23:25 UTC, apocales approved these changes

2023-07-04 23:25 UTC, apocales commented on components/cards/Card/MessageFree.tsx
> +                            onClick={ ()=>{ setTipoEnvio(MESSAGE_TYPE.CONVERSACION) } }
como estándar para el futuro, tratemos de nombrar variables en ingles por convención, no es necesario modificarlo ahora, pero tengámoslo en cuenta para la migración del repo

2023-07-04 23:25 UTC, apocales commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
>  };
deberíamos mover los types a un directorio de types y no definirlos dentro de los componentes, para que cada archivo tenga bien definida su responsabilidad, igual no es necesario modificar ahora, considerémoslo al migrar el repo

2023-07-05 01:23 UTC, alfredopuertacl approved these changes

2023-07-05 01:26 UTC, merged