Feature/improve texts and csv
Franbarbier/dragonchat-front pull request #77
Opened 2023-06-28 17:18 UTC by NicolasArias1

Se modifican algunos textos
Se fixea varias cosas pendientes de csv

2023-06-28 17:19 UTC, NicolasArias1 commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +            onChange={(e) => (e.target.files && e.target.files.length) && onDropFn(e.target.files[0])}
estos y similares tienen que quedar así, ya que si e.target.files es undefined, no sigue hacia delante

en caso de dejarlo con e.target.files?.length, estaría invocando length en un undefined y rompe

2023-06-28 17:27 UTC, NicolasArias1 commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +              onDrop={e => e.dataTransfer.files.length > 0 && handleDrop(e.dataTransfer.files[0], e)}
acá files no es nunca undefined

2023-06-28 17:31 UTC, Franbarbier commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +      <Notification {...notification} />
este notification aca no va, porque el modal tiene la posicion relativa, entonces el top: 5% y left: 5% de la notificacion queda como adentro del modal, y no en la esquina de la pantalla. Hay que mandarlo al padre (<CardsContFree />) y pasarlo el state de notification como prop

2023-06-28 18:12 UTC, alfredopuertacl requested changes

2023-06-28 18:12 UTC, alfredopuertacl commented on components/RecoverPasswordView/RecoverPasswordView.tsx
> +                  text="Guardar cambios"
aca ponle solo "Continuar"

2023-06-28 22:20 UTC, apocales commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +            onChange={(e) => (e.target.files && e.target.files.length) && onDropFn(e.target.files[0])}
perfecto

2023-06-28 22:23 UTC, apocales commented on components/cards/ModalImportContacts/ModalImportContacts.tsx
> +          setParsedCsvData(data.filter(d => d.nombre?.replaceAll(' ', '') !== '' && d.numero?.replaceAll(' ', '') !== ''))
esto es solo una consulta porque no se muy la intension del replaceAll... aqui no nos serviria un trim()?

2023-06-29 00:28 UTC, alfredopuertacl approved these changes

2023-06-29 00:29 UTC, merged