Feature/3dif messages
Franbarbier/dragonchat-front pull request #81
Opened 2023-07-07 22:34 UTC by Franbarbier

Componente para agregar alternativas del mensaje enviado.

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-07-08 02:59 UTC, apocales requested changes

2023-07-08 02:59 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +}
para los componentes nuevos hagamos una carpeta de types para dejar las definiciones de las props y otros

2023-07-08 02:59 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                }} />
tratemos de dejar la vista lo mas limpia posible, movamos el método onchange fuera del return, pasemos el index y el evento como parámetros a una función handler

2023-07-08 02:59 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                    }
tratemos de dejar la vista lo mas limpia posible, movamos el metodo onclick fuera del return, pasemos el index y el evento como parámetros a una función handler

2023-07-08 02:59 UTC, apocales commented on components/cards/CardsContFree.tsx
> +        function hasEmptyString() { return messages.some((str) => str === ''); }
hagamos una util para validar si un string es empty, porque también tenemos que validar casos como que no tenga espacios blancos, no sea nulo o undefined, y esta nueva función la llamamos desde esta función que creaste aca, aparte usemos la nomenclatura de arrow function, algo así...
```
const hasEmptyString = () => { return messages.some((str) => isEmptyString(str)); }
```
también podríamos dejar otra utilidad para validar los strings vacíos de un array de strings (que seria basicamente la funcion que hiciste, pero dejándola disponible para ser usada en otras partes)... pero esto es mas opcional

2023-07-08 02:59 UTC, apocales commented on components/cards/CardsContFree.tsx
>          return true
esto se puede resumir así...
```
return !(tipoEnvio == MESSAGE_TYPE.DIFUSION && !hasEmptyString() || tipoEnvio == MESSAGE_TYPE.CONVERSACION && activeSecuence != null && activeCard == 2)
```

2023-07-08 03:04 UTC, apocales requested changes

2023-07-08 03:04 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                <img src="/close.svg" onClick={
sería bueno mantener un enum con las rutas de imágenes mas comunes

2023-07-10 15:26 UTC, Franbarbier commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                    }
decis de hacer un utils por cada componente y poner las funciones ahi? creo que estaria bueno, quedaria mucho mas prolijo. O directamente definir todo dentro del componente?

2023-07-10 17:55 UTC, Franbarbier commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                }} />
Esto si te parece le mando asi ahora, y cuando empiece con la migracion saco todas las funciones del return

2023-07-11 23:32 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                }} />
bueno, pero igual recuerdame en proximos PRs porque probablemente dire lo mismo :(

2023-07-11 23:32 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                <img src="/close.svg" onClick={
bueno, en general la regla sería cuando usemos strings que se puedan repetir a lo largo de la aplicación y que hagan referencia a lo mismo... y la otra regla seria para englobar conceptos que tengan cierta lógica, pero igual no entendí bien tu respuesta, dices que lo aplicaras en el futuro y no en este PR?

2023-07-11 23:32 UTC, apocales commented on components/cards/BasicMessages/BasicMessages.tsx
> +                                    }
depende del caso, para cuando sean funciones genéricas (que se usen en varios lugares de la aplicación) que sea en una carpeta sobre la pagina, cuando sea de uso especifico de la pagina podemos dejarlo al mismo nivel

2023-07-12 17:21 UTC, alfredopuertacl approved these changes

2023-07-12 17:21 UTC, merged