Fix Edit user
Franbarbier/dragonchat-front pull request #85
Opened 2023-07-20 17:33 UTC by Franbarbier

Por el momento deje solo la opcion de editar pass + una notificacion de success o error a nivel front. El name y email lo dejo en satnd by hasta que el back este configurado para recibir esos datos tambien

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-07-20 23:16 UTC, alfredopuertacl approved these changes

2023-07-20 23:24 UTC, apocales requested changes

2023-07-20 23:24 UTC, apocales commented on api/apiUserController.tsx
>          if (password != '') {
la validación de este if podría mejorar, porque password tambien podria ser un espacio en blanco por ejemplo, creo que una mejor alternativa seria usar trim() 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim

aparte, no deberíamos devolver un error o algo asi si la validación no se cumple?

2023-07-20 23:24 UTC, apocales commented on components/EditUserProfileView/EditUserProfileView.tsx
> +      }
igual podríamos mostrar una notificación de error si el status es distinto de 200 o no? de hecho, se puede dar el caso de obtener un status distinto de 200 sin caer en el catch?

2023-07-21 17:04 UTC, Franbarbier commented on api/apiUserController.tsx
>          if (password != '') {
si, es verdad pero no lo veo necesario ahora. Igual lo voy a subir ne este PR. Pero era cuestion de poder cambiar la pass para tenerlo andando hasta la migracion. Hoy si mandas los campos vacios no te actualiza la pass. De todas formas le voy a meter un validador de cantidad de caracteres y espacio en blanco

2023-07-21 18:18 UTC, apocales requested changes

2023-07-21 18:18 UTC, apocales commented on api/apiUserController.tsx
>          if (password != '') {
bueno, dejemos el tema del envío del error pendiente, pero creo que agregar el trim si deberíamos hacerlo ahora

2023-07-21 18:18 UTC, apocales commented on components/EditUserProfileView/EditUserProfileView.tsx
> +      }
no entendi aca tu respuesta XD

2023-07-24 22:45 UTC, merged