Feature/stripe success
Franbarbier/dragonchat-front pull request #88
Opened 2023-09-15 01:11 UTC by Franbarbier

Hice el caminito:
Cae al login > se fija si hay stride session id como parametro > lo valida con la api de stripe > si esta ok y se logea > (falta el endpoint) se dispara la data al back: plan de stripe + usuario > se notifca al usuario y se elimina la cookie de stripe
---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-09-20 00:17 UTC, NicolasArias1 commented on pages/login.tsx
> +        session_data = await handleStripeSession(session_id) as string
acá está duplicado? y porqué as string, retorna un "" o un objeto, entonces no debería ser un string, sino un objeto o null

2023-09-21 02:26 UTC, apocales requested changes

2023-09-21 02:26 UTC, apocales commented on pages/dash.tsx
> +  );
esto ya se hacia en el middleware, porque se valida nuevamente acá?

2023-09-21 02:26 UTC, apocales commented on pages/login.tsx
> +        }
creo que esto debería estar en la vista del checkout y desde el lado del servidor

2023-09-21 02:26 UTC, apocales commented on utils/crypto.ts
> +const KEY = "12312312312312369312312312312312";
al menos estos 2 valores deberian ser parte del .env

2023-09-21 02:26 UTC, apocales commented on utils/stripe.ts
> +
no usaremos un endpoint que actualice directamente el plan, se usaran los endpoints ya existentes de login y registro a los cuales se les añadira lo siguiente al contrato
```
subscription: {
  session_id: string; // session de stripe
  product_id: string; // id del producto
}
```
cuando estos datos vayan definidos se actualizara el plan del usuario, si no, realizara el login o el registro solamente

2023-11-02 21:39 UTC, merged