Mantenimiento on/off
Franbarbier/dragonchat-front pull request #92
Opened 2023-11-03 17:37 UTC by Franbarbier

---
## *  **Importante**

El front busca del .env un "NEXT_PUBLIC_MAINTENANCE = true"

cualquier otro valor lo toma como mantenimiento false, si el valor es "true", lo toma como true.

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-11-03 19:38 UTC, alfredopuertacl commented
@Franbarbier funciona bien, solo un detalle de diseño que en las patantallas de notebook, se ve asi:

2023-11-04 00:41 UTC, apocales requested changes

2023-11-04 00:41 UTC, apocales commented on middleware.ts
> +  if (!req.nextUrl.pathname.startsWith(ROUTES.LOGIN) && !authCookie && !req.nextUrl.pathname.startsWith(ROUTES.SIGN_UP) && !req.nextUrl.pathname.startsWith(ROUTES.RECOVER) && !req.nextUrl.pathname.st
creo que aquí faltó la condición de `MAINTENANCE == "true"` no? igual de todas formas seria mejor pasar este valor a un booleano real para la comparación, algo así como
```
const maintenance = MAINTENANCE === "true"
```
y luego usar maintenance directamente como booleano en todos los otros lugares

2023-11-05 00:26 UTC, NicolasArias1 commented on components/Maintenance/Maintenance.tsx
> +                <p>Regresa dentro de un rato para continuar contactando y dominando tu mercado.</p>
envolvamos todos los strings en llaves y comillas

2023-11-05 00:27 UTC, NicolasArias1 commented on components/Maintenance/Maintenance.tsx
> +            <img src="dragonchat_dragon_tecnico.webp" />
estos strings a enums

2023-11-05 00:27 UTC, NicolasArias1 commented on components/Maintenance/Maintenance.tsx
> +
1 enter entre cosas

2023-11-05 00:28 UTC, NicolasArias1 commented on constants/index.ts
> +export const MAINTENANCE = process.env.NEXT_PUBLIC_MAINTENANCE  ;
acá podríamos ponerle un `|| false` y nos ahorramos todos los == 'true',

2023-11-05 00:31 UTC, NicolasArias1 commented on middleware.ts
> +  matcher: ["/dash", "/qr", "/premium", "/login", "/user/edit", "/signup",  "/recover_password",  "/new_password"],
no sé si valga la pena poner los middlewares en estas páginas "tan sencillas"

para mi les usaría un getServerSideProps y nos ahorramos varias cosas

2023-11-05 00:33 UTC, NicolasArias1 commented on components/Maintenance/Maintenance.tsx
> +
no enter al comienzo de archivo

2023-11-05 00:34 UTC, NicolasArias1 commented on components/LoginView/LoginView.tsx
> +                            } }>Regístrate</span>
acá creo que bastaría con un `onClick={() => !MAINTENANCE && Router.push('/signup')}`

2023-11-05 00:35 UTC, NicolasArias1 commented on components/LoginView/LoginView.tsx
> +                        disable={ MAINTENANCE == "true" && true}
`disable={MAINTENANCE}`

sino

`disable={Boolean(MAINTENANCE)}`

2023-11-05 00:36 UTC, NicolasArias1 commented on components/LoginView/LoginView.tsx
> +        }
esto quizá podríamos ponerlo dentro del mismo componente no? porque dudo que querramos mostrar el componente sino

2023-11-09 23:09 UTC, NicolasArias1 commented on middleware.ts
> +  if (!req.nextUrl.pathname.startsWith(ROUTES.LOGIN) && !authCookie && !req.nextUrl.pathname.startsWith(ROUTES.SIGN_UP) && !req.nextUrl.pathname.startsWith(ROUTES.RECOVER) && !req.nextUrl.pathname.st
se modificó el if de maintence

2023-11-10 00:13 UTC, apocales approved these changes

2023-11-10 00:36 UTC, alfredopuertacl approved these changes

2023-11-10 12:47 UTC, merged