handle 500 a wppConnect
Franbarbier/dragonchat-front pull request #93
Opened 2023-11-03 19:16 UTC by Franbarbier

Si el connect a wpp da 500, resetea el boton de "generando QR" para que no quede congelado

---
## *  **Importante**

### **¡ Gracias por contribuir en el repositorio de *dragon-chat* !**

2023-11-04 00:26 UTC, apocales requested changes

2023-11-04 00:26 UTC, apocales commented on api/apiSenderWhatsappController.tsx
> +                console.log(response)
igual no es necesario guardar el resultado en una variable si no lo estamos usando, y recuerda quitar los console.log

2023-11-04 00:26 UTC, apocales commented on components/QrCard/QrCard.tsx
> +        const dataConnection = await apiSenderWhatsappController.connect(accessToken)
según la modificación en el archivo `api/apiSenderWhatsappController.tsx` ya no se esta retornando el valor por lo que `dataConnection` siempre sería undefined aca

2023-11-09 21:21 UTC, Franbarbier commented on components/QrCard/QrCard.tsx
> +        const dataConnection = await apiSenderWhatsappController.connect(accessToken)
Tenes razon, ahi corregi. Deje el response porque si no llega a poder generarse la instancia de wpp. No hay nada que le diga al front que pase de "Generando QR" a "Generar QR" (visualmente, que es el estado nativo donde el usuario puede cliquear
)

2023-11-09 21:40 UTC, alfredopuertacl approved these changes

2023-11-10 00:17 UTC, apocales approved these changes

2023-11-10 12:44 UTC, merged